# Page settings

baseURL = "https://jtsoar.es/"
languageCode = "en"
title = "Resume for João Trigo Soares"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-61989966-1"

publishDir = "../"

[params]
    author = "suvl"
    description = "Resume for João Trigo Soares"

    primaryColor = "#546db6"
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "João Trigo Soares"
        tagline = "DevOps Engineer"
        avatar = "avatar.jpg"


    [params.contact]
        enable = true
        location = "Lisbon, Portugal"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:joao@jtsoar.es"
        text = "joao@jtsoar.es"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "jtsoar.es"
        text = "jtsoar.es"





    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "[Kubernetes](https://github.com/kubernetes/community) from 1.11 to latest stable"
        [[params.skills.list.items]]
        details = "Kubernetes Engines: [Rancher](https://rancher.com/), [GKE](https://cloud.google.com/kubernetes-engine), [AKS](https://azure.microsoft.com/en-gb/services/kubernetes-service/)"
        [[params.skills.list.items]]
        details = "[CRI](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md): Docker, containerd, CRI-O, (podman)"
        [[params.skills.list.items]]
        details = "[SMI](https://smi-spec.io/): istio"
        [[params.skills.list.items]]
        details = "[CNI](https://github.com/containernetworking/cni): Calico"
        [[params.skills.list.items]]
        details = "CI/CD: Jenkins and Azure DevOps"
        [[params.skills.list.items]]
        details = "Linux administration: ubuntu server, rancherOS, CentOS, debian"
        [[params.skills.list.items]]
        details = "Security: PKI, Active Directory, IAM"
        [[params.skills.list.items]]
        details = "Clouds: Azure, Google Cloud Platform, civo, Digitalocean, OVH"
        [[params.skills.list.items]]
        details = "DBs/KV: MongoDB, SQL Server, Redis, etcd"
        [[params.skills.list.items]]
        details = "Distributed Storage: [Ceph](https://ceph.io/) (block, object, filesystem)"
        [[params.skills.list.items]]
        details = "Message Systems: RabbitMQ, MQTT (Mosquitto)"
        [[params.skills.list.items]]
        details = "Windows server 2008/2012/2016"
        [[params.skills.list.items]]
        details = "Object-oriented: C#, Golang"
        [[params.skills.list.items]]
        details = "(Web) frameworks: ASP.NET, .NET framework, .NET core"
        [[params.skills.list.items]]
        details = "Design and implement distributed software"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"
        [[params.skills.list.items]]
        details = "Some frontend capabilities that are rusty but present"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "Faculty of Engineering - University of Porto"
        dates = "2009 - 2011"
        [[params.education.list]]
        degree = "BSc in Engineering Sciences"
        university = "Faculty of Engineering - University of Porto"
        dates = "2006 - 2009"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Portuguese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "3D printing"
        [[params.interests.list]]
        name = "IoT and electronicals"
        [[params.interests.list]]
        name = "Trekking"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Classical Music"


    [params.summary]
        enable = true
        text = """I've started my carreer as an IT consultant at Accenture, working for the Resources business (electricity, petrol). I've dedicated four years to 
            helping that companies with digital transformations and paperless workflows. My work was around Windows and ASP.NET software, namely Sharepoint and Windows Server. \
            I was promoted up to the role of Senior Developer.
            After that I started as a backend developer on one of the biggest telcos in Portugal. There I've helped implement scalable solutions to support the \
            TV multimedia business. Notable works include backends for user profiles and preferences, work in the cloud-based \
            [Personal View Recorder](https://en.wikipedia.org/wiki/Digital_video_recorder) engine, a new Auto Configuration System \
            based on the [XMiDT](https://comcast.github.io/#xmidt-projects) stack, and a new [Automatic Speech Recognition](https://en.wikipedia.org/wiki/Automatic_speech_recognition) \
            system using Azure's LUIS apis. I got up to Lead Developer.
            When the need for moving to the cloud and DevOps transformation arised I was called upon changing roles and started my current position as a DevOps Engineer. I'm contributing to \
            DevOps changes like adopting containerization, CI/CD, GitOps, automation (e.g. infrastructure-as-code, jmeter tests), hybrid infrastructure (on prem + cloud), distributed storage, \
            monitoring and self-healing systems.
            \n\nI'm a Certified Kubernetes Administrator with ID `LF-7j6a6nkfxw`. I'm also a Certified Kubernetes Application Developer with ID `LF-aqpmniufwu`. I'm enrolled in the CKS certification and plan to get it sometime around 2021.
            You can check my certificates [at the Linux Foundation website](https://training.linuxfoundation.org/certification/verify)."""







    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "2018 - Present"
        company = "NOS Inovação"
        details = "This challenge was created from the need to make NOS evolve and walk towards integrated microservices' architectures and having it orchestrated. We have fully embraced the CNCF, OSS and container solutions, having Kubernetes at the center of agile but resilient and tolerant systems. My mission is to advocate towards adopting Cloud Native architectures, and implementing those to gather success stories and lessons learned. I'm also working on \"lift-and-shift\" projects that try and get on premise workloads to the cloud. I'm trying to keep up with all CN ecosystem, specially by taking part of KubeCon and other conferences (Cloud Native Kitchen, Software Circus, ...). Some relevant success stories I might think of may be: implementing and maintaining a CEPH distributed storage cluster, GitOps for Kubernetes and HAProxy with Flux, Jenkins and haproxy-wi, implementing E2E workloads using AKS and/or GKE, advocating for service mesh integrations with Istio."
        [[params.experience.list.items]]
        details = "Kubernetes"
        [[params.experience.list.items]]
        details = "CRIs (docker, containerd, cri-o)"
        [[params.experience.list.items]]
        details = "Ingress software (nginx, haproxy, envoy)"
        [[params.experience.list.items]]
        details = "Monitoring software (prometheus, alertmanager, grafana, ...)"
        [[params.experience.list.items]]
        details = "Distributed Storage (CEPH, Rook)"
        [[params.experience.list.items]]
        details = "Logging and events (Elasticsearch, Logstash, Kafka, Vector, ...)"
        [[params.experience.list.items]]
        details = "GitOps and Policies (OPA, Gitlab, Jenkins)"
        [[params.experience.list.items]]
        details = "IaC and configuration (Terraform, Ansible)"
        [[params.experience.list.items]]
        details = "Cloud Infrastructure and Implementation (GCP (GKE), Azure (AKS))"
        [[params.experience.list.items]]
        details = "Golang, shell/ash/bash (preferabily POSIX), fish"
        [[params.experience.list.items]]
        details = "Security (gVisor, Sealed Secrets)"

        [[params.experience.list]]
        title = "Lead Software Engineer"
        dates = "2017 - 2018"
        company = "NOS Inovação"
        details = "At this time I took a leading role, in a sense of having extensive autonomy on technical decisions regarding the techical paths of some existing projects but also starting some new ones. These were times that saw the rise of `dotnet core` and the adoption of conainerization and the move of typical Windows workloads to Linux. I worked on core projects like the [EPG](https://en.wikipedia.org/wiki/Electronic_program_guide) APIs, the [NAME project](https://github.com/nosinovacao/name-sdk), an ACS solution (based on [WebPA](https://github.com/xmidt-org/webpa)) and selfservice APIs that allow clients to chang their TV subscriptions. It was also a time of starting the move towards microservices and breaking monolith applications."
        [[params.experience.list.items]]
        details = "(same as the previous one)"
        [[params.experience.list.items]]
        details = ".NET Core"
        [[params.experience.list.items]]
        details = "Docker"
        [[params.experience.list.items]]
        details = "Rancher's Cattle"

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2015 - 2017"
        company = "NOS Inovação"
        details = "I got challenged to do some rework on existing APIs on the Social aspects of the TV experience. These were some rough applications that needed both some refactoring to get a simpler architecture and the implementation of newer features that'd be required for the Next Generation of   TV products (that then became known as UMA). It was also a great experience as I started working with NoSQL and defining REST APIs (rather than just consuming them)."
        [[params.experience.list.items]]
        details = "ASP.NET"
        [[params.experience.list.items]]
        details = "C#"
        [[params.experience.list.items]]
        details = ".NET Framework"
        [[params.experience.list.items]]
        details = "MongoDB"
        [[params.experience.list.items]]
        details = "SQL Server (using Entity Framework)"
        [[params.experience.list.items]]
        details = "RabbitMQ"
        [[params.experience.list.items]]
        details = "Postman, Swagger, jmeter, ..."
        [[params.experience.list.items]]
        details = "Backend web development"


        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2011 - 2015"
        company = "Accenture Technology Solutions"
        details = """I was assigned to that unit inside the Lisbon Delivery Center. I was then allocated to the SharePoint team.

There I was involved in developing diverse SharePoint solutions, for intranet and public portals. The biggest being the EDP intranet, awarded with the Europe's best at the 2013 Digital Communication Awards. That project involved scaling for 12k employees using it for booking vehicles, using team sites, managing schedules and vacation days, receiving company news, whatnot.

There were other projects, of a smaller nature. One project I'd like to highlight was related to the POS systems of all stores of a major telecom provider. The company had bought highly advanced terminals but those were misused just for simple payments. That project integrated their billing and store front systems to take advantage of paperless signatures, integrated payment receipts and advanced reporting features."""
        [[params.experience.list.items]]
        details = "Sharepoint, ASP.NET, C#"
        [[params.experience.list.items]]
        details = "Windows Server 2008/2012 R2, SQL Server"
        [[params.experience.list.items]]
        details = "Full-stack web development"

        [[params.experience.list]]
        title = "Researcher"
        dates = "2010 - 2011"
        company = "INESC TEC"
        details = """I integrated the Computer Vision team while developing my master's thesis. My project intended to reconstruct rough 3D models from freely taken pictures. \
        It was a sub-project of a bigger effort from the team \to consistently measure the resulting effects of mastectomy interventions. The results would contribute to find \
        and develop methods where the aesthetic impact was minimized while the change of success was higher.\n\n[Check out the full thesis](https://repositorio-aberto.up.pt/handle/10216/63333)."""











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "NAME"
        meta = "Open Source"
        tagline = "A dependencies management library designed to expose and access dependencies information."

        [[params.projects.list]]
        title = "Network PVR"
        meta = "Proprietary: NOS Inovação"
        tagline = "Allows service providers to manage the complete recording ecosystem in a flexible manner. It also eliminates the need for individual user storage space in set-top boxes by providing a central location where all recorded programs could be stored and easily accessible. Catch up TV 7 days in the past. The biggest change since moving from black and white to color TV."

        [[params.projects.list]]
        title = "edpOn Intranet"
        meta = "Proprietary: EDP"
        tagline = "The edpOn intranet is the entry point and main communication channel for the more than 12 000 employees of EDP, in three languages and 5 continents."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/suvl"
        title = "suvl"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/joaotrigosoares"
        title = "joaotrigosoares"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/thegreatdevop"
        title = "@thegreatdevop"





